# Generated by Django 6.0.7 on 2026-07-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(max_length=100)),
                ('occupancy', models.CharField(blank=True, max_length=100, null=True)),
                ('construction_status', models.CharField(choices=[('planned', 'Planned'), ('under_construction', 'Under Construction'), ('complete', 'Complete')], default='complete', max_length=30)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_storeys', models.PositiveIntegerField(default=1)),
                ('plinth_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finishes', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=100, unique=True)),
                ('property_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Size in acres/hectares', max_digits=12)),
                ('property_user', models.CharField(blank=True, max_length=100, null=True)),
                ('property_tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=20)),
                ('ownership_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government'), ('trust', 'Trust')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='FloorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_label', models.CharField(help_text='e.g. Ground, 1st, Mezzanine', max_length=50)),
                ('floor_order', models.PositiveIntegerField(help_text='Used for sorting floors top to bottom')),
                ('floor_use', models.CharField(blank=True, max_length=100, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.buildingdetails')),
            ],
            options={
                'ordering': ['floor_order'],
            },
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_use', models.CharField(max_length=100)),
                ('topography', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('road_frontage', models.CharField(blank=True, max_length=100, null=True)),
                ('accessibility', models.CharField(blank=True, max_length=100, null=True)),
                ('utilities', models.CharField(blank=True, max_length=255, null=True)),
                ('zoning', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_details', to='properties.property'),
        ),
        migrations.CreateModel(
            name='UnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_type', models.CharField(help_text='e.g. 1-bedroom, office, retail', max_length=100)),
                ('unit_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('under_renovation', 'Under Renovation')], default='vacant', max_length=30)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.floordetails')),
            ],
        ),
    ]
