# Generated by Django 6.0.7 on 2026-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=100, unique=True)),
                ('property_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Size in acres/hectares', max_digits=12)),
                ('property_user', models.CharField(blank=True, max_length=100, null=True)),
                ('property_tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold')], max_length=20)),
                ('ownership_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government'), ('trust', 'Trust')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
