# Generated by Django 6.0.7 on 2026-07-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingdetails',
            options={'verbose_name_plural': 'Building Details'},
        ),
        migrations.AlterModelOptions(
            name='floordetails',
            options={'ordering': ['floor_order'], 'verbose_name_plural': 'Floor Details'},
        ),
        migrations.AlterModelOptions(
            name='landdetails',
            options={'verbose_name_plural': 'Land Details'},
        ),
        migrations.AlterModelOptions(
            name='unitdetails',
            options={'verbose_name_plural': 'Unit Details'},
        ),
    ]
