# Generated by Django 6.0.7 on 2026-08-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_size',
            field=models.DecimalField(decimal_places=4, help_text='Land size in hectares', max_digits=12),
        ),
    ]
