# Generated by Django 6.0.7 on 2026-08-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_type', models.CharField(max_length=100)),
                ('occupancy', models.CharField(blank=True, max_length=100, null=True)),
                ('construction_status', models.CharField(choices=[('planned', 'Planned'), ('under_construction', 'Under Construction'), ('complete', 'Complete')], default='complete', max_length=30)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_storeys', models.PositiveIntegerField(default=1)),
                ('plinth_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finishes', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Building Details',
            },
        ),
        migrations.CreateModel(
            name='FloorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_label', models.CharField(help_text='e.g. Ground, 1st, Mezzanine', max_length=50)),
                ('floor_order', models.PositiveIntegerField(help_text='Used for sorting floors top to bottom')),
                ('floor_use', models.CharField(blank=True, max_length=100, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='valuations.buildingdetails')),
            ],
            options={
                'verbose_name_plural': 'Floor Details',
                'ordering': ['floor_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('observations', models.TextField(blank=True, help_text='General notes from the inspection', null=True)),
                ('photos_taken', models.BooleanField(default=False)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_details', to='valuations.inspectiondetails'),
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_use', models.CharField(max_length=100)),
                ('topography', models.CharField(blank=True, max_length=100, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('road_frontage', models.CharField(blank=True, max_length=100, null=True)),
                ('accessibility', models.CharField(blank=True, max_length=100, null=True)),
                ('utilities', models.CharField(blank=True, max_length=255, null=True)),
                ('zoning', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='valuations.inspectiondetails')),
            ],
            options={
                'verbose_name_plural': 'Land Details',
            },
        ),
        migrations.CreateModel(
            name='UnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_type', models.CharField(help_text='e.g. 1-bedroom, office, retail', max_length=100)),
                ('unit_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('under_renovation', 'Under Renovation')], default='vacant', max_length=30)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='valuations.floordetails')),
            ],
            options={
                'verbose_name_plural': 'Unit Details',
            },
        ),
        migrations.CreateModel(
            name='ValuationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, help_text='e.g. Mortgage, Sale, Insurance, Rating', max_length=255, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_assignments', to='clients.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_assignments', to='properties.property')),
                ('valuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inspectiondetails',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='valuations.valuationassignment'),
        ),
        migrations.CreateModel(
            name='ValuationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_used', models.CharField(choices=[('cost', 'Cost Approach'), ('market', 'Market/Sales Comparison Approach'), ('income', 'Income Approach')], max_length=20)),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per sqm/unit used in the calculation, if applicable', max_digits=12, null=True)),
                ('valuation_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='valuations.valuationassignment')),
            ],
        ),
    ]
