# Generated by Django 6.0.7 on 2026-08-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiondetails',
            options={'verbose_name_plural': 'Inspection Details'},
        ),
        migrations.RemoveField(
            model_name='valuationresult',
            name='method_used',
        ),
        migrations.RemoveField(
            model_name='valuationresult',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='valuationresult',
            name='rate_used',
        ),
        migrations.RemoveField(
            model_name='valuationresult',
            name='valuation_amount',
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='reconciliation_notes',
            field=models.TextField(blank=True, help_text='Explanation of how the final value was reached, especially if multiple methods were combined', null=True),
        ),
        migrations.CreateModel(
            name='CostApproachDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('computed_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_approach', to='valuations.valuationresult')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeApproachDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cap_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('computed_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_approach', to='valuations.valuationresult')),
            ],
        ),
    ]
