# Generated by Django 6.0.7 on 2026-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0002_alter_inspectiondetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuationresult',
            name='final_value',
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='insurance_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reinstatement/insurance value', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuationresult',
            name='mortgage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='valuationresult',
            name='reconciliation_notes',
            field=models.TextField(blank=True, help_text='Explanation of how the values were reached, especially if multiple methods were combined', null=True),
        ),
    ]
