# Generated by Django 6.0.7 on 2026-08-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0002_inspectiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_used', models.CharField(choices=[('cost', 'Cost Approach'), ('market', 'Market/Sales Comparison Approach'), ('income', 'Income Approach')], max_length=20)),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per sqm/unit used in the calculation, if applicable', max_digits=12, null=True)),
                ('valuation_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='valuations.valuationassignment')),
            ],
        ),
    ]
