# Generated by Django 6.0.7 on 2026-08-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0003_remove_valuationresult_final_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='plinth_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plinth area in square metres', max_digits=12, null=True),
        ),
    ]
