# Generated by Django 6.0.7 on 2026-08-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0004_alter_buildingdetails_plinth_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiondetails',
            name='photos_taken',
        ),
    ]
