# Generated by Django 6.0.7 on 2026-08-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0005_remove_inspectiondetails_photos_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='inspection_photos/%Y/%m/')),
                ('category', models.CharField(choices=[('access_road', 'Access Road / Entrance'), ('subject_property', 'Subject Property'), ('adjacent_property', 'Adjacent Property'), ('other', 'Other')], max_length=30)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='valuations.inspectiondetails')),
            ],
        ),
    ]
