# Generated by Django 6.0.7 on 2026-08-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0006_inspectionphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionphoto',
            name='category',
            field=models.CharField(choices=[('access_road', 'Access Road / Entrance'), ('subject_property', 'Subject Property'), ('adjacent_property', 'Adjacent Property'), ('map_default', 'Location Map — Default/Terrain View'), ('map_satellite', 'Location Map — Satellite View'), ('map_directions', 'Location Map — Direction from Nearest City/Landmark'), ('other', 'Other')], max_length=30),
        ),
    ]
